### ISSUE TITLE
不知能否增加一些屏蔽站点

### ISSUE THREAD

**Issue by chen185102** [MikeWang000000/ad.js#12]
站点域名可以参考如下hosts文件，https://raw.githubusercontent.com/vokins/yhosts/master/hosts
像类似cnzz的统计站点其实可以屏蔽的吧^  ^

**Comment by MikeWang000000** [comment]
最近要考试，有点忙呵^_^
以后会考虑的。
其实你可以fork一下自己添加的。

**Comment by chen185102** [comment]
已fork，自己写了个python脚本来处理hosts了

**Comment by MikeWang000000** [comment]
现已增加。请重新设置以清除缓存。
如果有过度拦截问题欢迎汇报。
