### ISSUE TITLE
xp上优酷无效〜

### ISSUE THREAD

**Issue by 3322964** [MikeWang000000/ad.js#2]
浏览器是 chromium 30 〜 配合switchy omega 〜还是要等45秒〜

**Comment by MikeWang000000** [comment]
直接使用系统代理就行了。刚刚测试了下，没有发现以上问题哦。打开cdce.cf主页看下状态，检查是否正确配置。
![image](https://cloud.githubusercontent.com/assets/11748152/15651982/a6b54388-26b5-11e6-881f-4f97e31842a4.png)

**Comment by MikeWang000000** [comment]
今天用xp试了下，xp好像不支持CloudFlare SSL，请使用http协议，即`http://cdce.cf/ad.js`。
