### ISSUE TITLE
null

### ISSUE THREAD

**Issue by catshitz** [MikeWang000000/ad.js#8]

**Comment by MikeWang000000** [comment]
注释里面写的很清楚了啊，直接仿照前面的例子往后面加域名就行了。

**Comment by MikeWang000000** [comment]
abp的规则，理论上是可以导入到ad.js上的。但是我测试了下shExpMatch()函数在iOS上好像不起作用，就没法通过检查url拦截广告了。。不知道为什么。。所以导入了也没用。。
